version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/webapp
hooks:
  BeforeInstall:
    - location: codedeploy/beforeInstall.sh
      timeout: 3000
      runas: ubuntu
  ApplicationStart:
    - location: codedeploy/applicationStart.sh
      timeout: 3000
      runas: root
